/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type ScBalanceStruct = { address_: string; balance_: BigNumberish };

export type ScBalanceStructOutput = [string, BigNumber] & {
  address_: string;
  balance_: BigNumber;
};

export interface RegisterFormInterface extends utils.Interface {
  functions: {
    "exportByPage(uint16)": FunctionFragment;
    "getScBalance(address)": FunctionFragment;
    "getTotalCount()": FunctionFragment;
    "owner()": FunctionFragment;
    "register(string)": FunctionFragment;
    "registerOf(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "exportByPage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "register", values: [string]): string;
  encodeFunctionData(functionFragment: "registerOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "exportByPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RegisterForm extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RegisterFormInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    exportByPage(
      _pageNo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [ScBalanceStructOutput[]] & { scBalanceList_: ScBalanceStructOutput[] }
    >;

    getScBalance(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTotalCount(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { count_: BigNumber; totalPage_: BigNumber }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    register(
      _telegramId: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerOf(_address: string, overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  exportByPage(
    _pageNo: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ScBalanceStructOutput[]>;

  getScBalance(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

  getTotalCount(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { count_: BigNumber; totalPage_: BigNumber }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  register(
    _telegramId: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerOf(_address: string, overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    exportByPage(
      _pageNo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ScBalanceStructOutput[]>;

    getScBalance(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalCount(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { count_: BigNumber; totalPage_: BigNumber }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    register(_telegramId: string, overrides?: CallOverrides): Promise<boolean>;

    registerOf(_address: string, overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    exportByPage(
      _pageNo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getScBalance(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalCount(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    register(
      _telegramId: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerOf(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    exportByPage(
      _pageNo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getScBalance(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    register(
      _telegramId: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerOf(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
